<!-- File: src/Astrolabed.Ntp/Astrolabed.Ntp.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Astrolabed.Ntp</RootNamespace>
    <AssemblyName>Astrolabed.Ntp</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>Guidcruncher</Authors>
    <Description>Astrolabed Ntp Host</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="11.0.0-preview.7.26381.103" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Astrolabed.EventBus\Astrolabed.EventBus.csproj" />
    <ProjectReference Include="..\Astrolabed.Data\Astrolabed.Data.csproj" />
    <ProjectReference Include="..\Astrolabed.Core\Astrolabed.Core.csproj" />
  </ItemGroup>

</Project>
