/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardView: typeof import('./views/DashboardView.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    DhcpView: typeof import('./views/DhcpView.vue')['default']
    DnsView: typeof import('./views/DnsView.vue')['default']
    NetworkView: typeof import('./views/NetworkView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
