/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppDatePicker: typeof import('./components/AppDatePicker.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppToolbar: typeof import('./components/AppToolbar.vue')['default']
    BaseModal: typeof import('./components/BaseModal.vue')['default']
    CacheListView: typeof import('./views/CacheListView.vue')['default']
    DashboardView: typeof import('./views/DashboardView.vue')['default']
    DataGrid: typeof import('./components/DataGrid.vue')['default']
    DatePicker: typeof import('./components/DatePicker.vue')['default']
    DefaultLayout: typeof import('./layouts/DefaultLayout.vue')['default']
    DemoView: typeof import('./views/DemoView.vue')['default']
    DeviceType: typeof import('./components/DeviceType.vue')['default']
    DhcpView: typeof import('./views/DhcpView.vue')['default']
    DnsBenchmarksView: typeof import('./views/DnsBenchmarksView.vue')['default']
    DnsQueryView: typeof import('./views/DnsQueryView.vue')['default']
    DnsView: typeof import('./views/DnsView.vue')['default']
    HomeView: typeof import('./views/HomeView.vue')['default']
    LandingLayout: typeof import('./layouts/LandingLayout.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    LoginView: typeof import('./views/LoginView.vue')['default']
    NetworkView: typeof import('./views/NetworkView.vue')['default']
    Panel: typeof import('./components/Panel.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackedBarChart: typeof import('./components/StackedBarChart.vue')['default']
  }
}
