services:
  astrolabed:
    container_name: astrolabed
    hostname: astrolabed
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # DNS uses UDP port 53
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "68:68"
      - "123:123/udp"
      - "1080:1080"

    # Mount config so you can edit without rebuilding
    volumes:
      - ./src/Astrolabed/appsettings.Docker.json:/app/appsettings.json:ro
      - ../netdns-runtime/dns-hosts:/dns-hosts:ro
      - ../netdns-runtime/dns-lists:/dns-lists:ro

    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

    # Optional: run with host networking for maximum performance
    network_mode: host
