services:
  astrolabed-dns:
    image: docker.io/guidcruncher/astrolabed:latest
    container_name: astrolabed-dns-engine
    hostnamee: astrolabed-dns
    restart: unless-stopped

    # Bypasses Docker user-land proxy for minimal UDP latency
    # Note: When network_mode is host, ports section is ignored
    network_mode: host

    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    environment:
      - Logging__LogLevel__Default=Information
      - DnsEngine__ListenAddress__Address=0.0.0.0
      - DnsEngine__ListenAddress__Port=53
      - DnsEngine__ProcessingThreads=4

    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
      - ./settings/:/etc/astrolabed:ro

    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - NET_RAW
