services:
  astrolabed:
    container_name: astrolabed
    hostname: astrolabed
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped

    # DNS uses UDP port 53
    ports:
      - "1053:1053/tcp"
      - "1053:1053/udp"
      - "1067:1067/udp"
      - "1068:1068"
      - "1123:1123/udp"
      - "1080:1080"
      - "1081:1081"

    # Mount config so you can edit without rebuilding
    volumes:
      - ./src/Astrolabed/appsettings.Development.json:/app/appsettings.json:ro
      - ../netdns-runtime/dns-hosts:/dns-hosts:ro
      - ../netdns-runtime/dns-lists:/dns-lists:ro

    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - NET_RAW
      - NET_ADMIN
      - SYS_TIME
      - SYS_NICE

    # Optional: run with host networking for maximum performance
    network_mode: host
