<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Astrolabed.EventBus</RootNamespace>
    <AssemblyName>Astrolabed.EventBus</AssemblyName>
    <Version>1.0.0</Version>
    <Authors>Astrolabed</Authors>
    <Description>In-process low-latency event bus for cross-IHost communication.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="11.0.0-preview.7.26381.103" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="11.0.0-preview.7.26381.103" />
  </ItemGroup>

</Project>
