/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DbOptionsConfigForm: typeof import('./src/components/DbOptionsConfigForm.vue')['default']
    DhcpConfigForm: typeof import('./src/components/DhcpConfigForm.vue')['default']
    DhcpLeaseTab: typeof import('./src/components/DhcpLeaseTab.vue')['default']
    DnsConfigForm: typeof import('./src/components/DnsConfigForm.vue')['default']
    DnsLogsTab: typeof import('./src/components/DnsLogsTab.vue')['default']
    DnsLookupTab: typeof import('./src/components/DnsLookupTab.vue')['default']
    LanDevicesTab: typeof import('./src/components/LanDevicesTab.vue')['default']
    LoggingConfigForm: typeof import('./src/components/LoggingConfigForm.vue')['default']
    MetricsConfigForm: typeof import('./src/components/MetricsConfigForm.vue')['default']
    NetworkScannerConfigForm: typeof import('./src/components/NetworkScannerConfigForm.vue')['default']
    NtpConfigForm: typeof import('./src/components/NtpConfigForm.vue')['default']
    NtpLookupTab: typeof import('./src/components/NtpLookupTab.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebUiConfigForm: typeof import('./src/components/WebUiConfigForm.vue')['default']
    WhiptailButton: typeof import('./src/components/WhiptailButton.vue')['default']
    WhiptailCalendar: typeof import('./src/components/WhiptailCalendar.vue')['default']
    WhiptailCheckbox: typeof import('./src/components/WhiptailCheckbox.vue')['default']
    WhiptailCheckboxGroup: typeof import('./src/components/WhiptailCheckboxGroup.vue')['default']
    WhiptailChecklist: typeof import('./src/components/WhiptailChecklist.vue')['default']
    WhiptailCombobox: typeof import('./src/components/WhiptailCombobox.vue')['default']
    WhiptailDataGrid: typeof import('./src/components/WhiptailDataGrid.vue')['default']
    WhiptailDialog: typeof import('./src/components/WhiptailDialog.vue')['default']
    WhiptailFormGroup: typeof import('./src/components/WhiptailFormGroup.vue')['default']
    WhiptailGauge: typeof import('./src/components/WhiptailGauge.vue')['default']
    WhiptailInput: typeof import('./src/components/WhiptailInput.vue')['default']
    WhiptailInputBox: typeof import('./src/components/WhiptailInputBox.vue')['default']
    WhiptailLabel: typeof import('./src/components/WhiptailLabel.vue')['default']
    WhiptailList: typeof import('./src/components/WhiptailList.vue')['default']
    WhiptailLoginBox: typeof import('./src/components/WhiptailLoginBox.vue')['default']
    WhiptailMenuList: typeof import('./src/components/WhiptailMenuList.vue')['default']
    WhiptailMessageBox: typeof import('./src/components/WhiptailMessageBox.vue')['default']
    WhiptailRadioGroup: typeof import('./src/components/WhiptailRadioGroup.vue')['default']
    WhiptailRadiolist: typeof import('./src/components/WhiptailRadiolist.vue')['default']
    WhiptailSelect: typeof import('./src/components/WhiptailSelect.vue')['default']
    WhiptailTabs: typeof import('./src/components/WhiptailTabs.vue')['default']
    WhiptailTextarea: typeof import('./src/components/WhiptailTextarea.vue')['default']
    WhiptailTitlebar: typeof import('./src/components/WhiptailTitlebar.vue')['default']
    WhiptailYesNo: typeof import('./src/components/WhiptailYesNo.vue')['default']
  }
}
