// File: src/Astrolabed.Dns/Services/IDnsQueryProcessor.cs
using System.Net;

namespace Astrolabed.Dns.Services;

/// <summary>
/// Contract for processing raw DNS queries.
/// </summary>
public interface IDnsQueryProcessor
{
    /// <summary>
    /// Processes an incoming raw DNS query packet from a client end point.
    /// </summary>
    /// <param name="rawPacket">The raw DNS wire format payload buffer.</param>
    /// <param name="clientEndpoint">The remote endpoint of the requesting client.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The generated byte array DNS response, or null if parsing fails.</returns>
    Task<byte[]?> ProcessRequestAsync(ReadOnlyMemory<byte> rawPacket, EndPoint clientEndpoint, CancellationToken ct);
}
