// File: src/Astrolabed.Dns/Services/IDnsQueryProcessor.cs
using System.Net;

using Astrolabed.Dns.Models;

namespace Astrolabed.Dns.Services;

/// <summary>
/// Contract for processing raw DNS queries.
/// </summary>
public interface IDnsQueryProcessor
{
    /// <summary>
    /// Processes an incoming raw DNS query packet from a client end point.
    /// </summary>
    /// <param name="rawPacket">The raw DNS wire format payload buffer.</param>
    /// <param name="clientEndpoint">The remote endpoint of the requesting client.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The generated byte array DNS response, or null if parsing fails.</returns>
    Task<byte[]?> ProcessRequestAsync(ReadOnlyMemory<byte> rawPacket, EndPoint clientEndpoint, CancellationToken ct);

    /// <summary>
    /// Processes a DNS query given a target domain string and query type identifier.
    /// </summary>
    /// <param name="domain">The target domain name (e.g., "example.com").</param>
    /// <param name="type">The numerical DNS record type (e.g., 1 for A, 28 for AAAA).</param>
    /// <param name="clientEndpoint">The remote endpoint of the requesting client.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The generated DNS response, or null if parsing/processing fails.</returns>
    Task<DnsWireMessage?> ProcessQueryAsync(
        string domain,
        DnsType type,
        EndPoint clientEndpoint,
        CancellationToken ct = default);

}
